In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import datetime
from datetime import timedelta


from transplant.config import *
from transplant.data.dataset import Dataset


from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

import random


%matplotlib inline

In [2]:
from transplant.data.validation_tree import *

In [3]:
validation = Validation()

In [4]:
#Test the validation tree for one instance

In [5]:
data_static = validation.get_static()
data_dynamic = validation.get_dynamic()

In [6]:
id_test = random.choice(data_static.id_patient.values)
id_test

178

In [7]:
validation.decision_empirique(id_patient=id_test, 
                              data_static=data_static, 
                              data_dynamic=data_dynamic,
                              regle_nan=True, 
                              drop_NMT=True)

'Transfer to ICU with ECMO and mechanical ventilation'

In [8]:
data_static_id=validation.get_static_id(data_static, id_=id_test)
data_static_id.immediate_extubation.values[0]

1

In [9]:
#apply the validation tree for all the id patients and get score performance

In [10]:
df_results = validation.get_results_dataframe(regle_nan=True, drop_NMT=True)

In [11]:
df_results.head()

id_patient  immediate_extubation  target  \
0           1                     0       0   
1           2                     1       1   
2           3                     0       0   
3           4                     0       1   
4           5                     0       0   

                                         result_tree  bianary_result_tree  
0  Transfer to ICU with ECMO and mechanical venti...                    0  
1        Transfer to ICU with mechanical ventilation                    0  
2  Transfer to ICU with ECMO and mechanical venti...                    0  
3        Transfer to ICU with mechanical ventilation                    0  
4  Transfer to ICU with mechanical ventilation an...                    0

In [12]:
df_results.result_tree.value_counts()

Transfer to ICU with ECMO and mechanical ventilation           142
Transfer to ICU with mechanical ventilation and iNO therapy     83
Transfer to ICU with standard oxygen therapy or NIV             59
Transfer to ICU with mechanical ventilation                     46
Name: result_tree, dtype: int64

In [13]:
#predictions of the tree vs 'immediate_extubation'

In [14]:
validation.get_score_and_confusion_matrices_for_immediate_ext(df_results)

accuracy:  0.693939393939394


matrice de confusion
[[193  23]
 [ 78  36]]


matrice de confusion en pct
[[58.48484848  6.96969697]
 [23.63636364 10.90909091]]


In [15]:
#predictions of the tree vs target

In [16]:
validation.get_score_and_confusion_matrices_for_target(df_results)

accuracy:  0.6121212121212121


matrice de confusion
[[166  23]
 [105  36]]


matrice de confusion en pct
[[50.3030303   6.96969697]
 [31.81818182 10.90909091]]


In [17]:
df_results_nan_false = validation.get_results_dataframe(regle_nan=False, drop_NMT=True)

In [19]:
validation.get_score_and_confusion_matrices_for_immediate_ext(df_results_nan_false)

accuracy:  0.693939393939394


matrice de confusion
[[193  23]
 [ 78  36]]


matrice de confusion en pct
[[58.48484848  6.96969697]
 [23.63636364 10.90909091]]
